### ISSUE TITLE
How to install this package?

### ISSUE THREAD

**Issue by gustawdaniel** [Skarsnik/perl6-gumbo#8]
Command:

    zef install Gumbo

freeze on
 
    ===> Searching for: Gumbo
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json

**Comment by Skarsnik** [comment]
hm, this is weird, I did not upload this module on CPAN, so it should use the github repo

**Comment by jubilatious1** [comment]
@gustawdaniel , is this issue resolved and ready to close? 

I recently installed **perl6-gumbo** using zef and it now works. (See https://github.com/Skarsnik/perl6-gumbo/issues/12#issuecomment-532821954). I just think @ugexe 's zef is updating cpan mirrors whenever a module install is requested, and  regardless of the install cpan is on zef's search-path and that's why it checks cpan first (I gave zef no instructions otherwise). Also, by updating mirrors, zef could be preparing to search for Gumbo dependencies (e.g. @supernovus 's XML module) on cpan. 

```
mbook:~ homedir$ zef install Gumbo
===> Searching for: Gumbo
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: XML
===> Testing: XML:ver<0.3.0>:auth<Timothy Totten>
===> Testing [OK] for XML:ver<0.3.0>:auth<Timothy Totten>
===> Testing: Gumbo:ver<1.0>:auth<Sylvain Colinet>
```

**Comment by ugexe** [comment]
> zef is updating cpan mirrors whenever a module install is requested, and regardless of the install 

Correct (technically every [auto-update](https://github.com/ugexe/zef/blob/e73897378b36cbf53f2ed8d98363d94bac70767d/resources/config.json#L44) hours as noted [here](https://github.com/ugexe/zef/blob/a606f316324187775fe49ea21ad6881dce4751f6/README.pod#update))

> hm, this is weird, I did not upload this module on CPAN, so it should use the github repo

How could zef know the module is not on cpan without first downloading the `cpan.json` file? And similarly for `p6c.json`

---

This seems to be the result of when the previous p6c server, which originally provided the `p6c.json` mirror, went kaput and left zef waiting indefinitely for a reponse. That mirror works again, and other versions of zef changed to using a mirror hosted on github, so this issue is likely resolved.
